version: '3'
services:
    db:
        # name: 'postgres'
        image: 'postgres:latest'
        expose:
            - '5432'
        restart: 'always'
        networks:
            djangonetwork:
        environment:
            - POSTGRES_DB=ranker
            - POSTGRES_USER=ranker
            - POSTGRES_PASSWORD=password
        volumes:
            - ./data/db:/var/lib/postgresql/data
    npm:
        build:
            context: .
            dockerfile: Dockerfile-frontend
        restart: 'always'
        networks:
            djangonetwork:
        volumes:
            - ./dist:/code/dist
        ports:
            - '3000:3000'
        command: "npm run serve -- --port 3000"
    web:
        build:
            context: .
            dockerfile: Dockerfile-backend
        ports:
            - '80:80'
        restart: 'always'
        volumes:
            - .:/code
        depends_on:
            - db
            - npm
        links:
            - db:db
        networks:
            djangonetwork:
networks:
    djangonetwork:
        driver: bridge
        # services:
        #     db:
        #         image: postgres
        #         ports:
        #             - '5432'
        #         restart: always
        #         environment:
        #             - POSTGRES_DB=ranker
        #             - POSTGRES_USER=ranker
        #             - POSTGRES_PASSWORD=password
        #         volumes:
        #             - ./data/db:/var/lib/postgresql/data
        #         networks:
        #             djangonetwork:
        #     web:
        #         build: .
        #         command: python3 manage.py runserver 0.0.0.0:8000
        #         volumes:
        #             - .:/code
        #         ports:
        #             - "8000:8000"
        #         environment:
        #             - POSTGRES_NAME=ranker
        #             - POSTGRES_USER=ranker
        #             - POSTGRES_PASSWORD=password
        #         depends_on:
        #             - db
        #         networks:
        #             djangonetwork:
        #     networks:
        #         djangonetwork:
